# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ui_0fUAbcjcgiAtTn9BRtwiUFO2JXeOe
"""

import streamlit as st

# Configuración de la página
st.set_page_config(page_title="CV de María Fe", page_icon="📄")

# Título principal
st.title("💼 Currículum Vitae")

# Información personal
st.header("👤 Información Personal")
st.subheader("María Fe Lidia Jacha La Pierre")
st.write("Estudiante de tercer año de la carrera de Comunicación Audiovisual en la Pontificia Universidad Católica del Perú. Becaria Lucet por excelencia académica. Soy proactiva, responsable, organizada y carismática. Me gusta tomar la iniciativa para crear nuevos proyectos que se ajusten a los intereses y necesidades.")
st.write("📧 mariafejachalapierre@gmail.com")
st.write("📱 923 315 527")

# Educación
st.header("🎓 Educación")
st.write("**Pontificia Universidad Católica del Perú**")
st.write("Carrera: Comunicación Audiovisual (Marzo 2023 - Actualidad)")
st.write("🏅 Becaria Lucet por excelencia académica")

# Habilidades
st.header("🛠️ Habilidades")
st.write("- Microsoft Office: Word, PowerPoint y Excel")
st.write("- Trabajo en equipo")
st.write("- Liderazgo")

# Idiomas
st.header("🌍 Idiomas")
st.write("- Español (nativo)")
st.write("- Inglés (avanzado)")
st.write("- Italiano (avanzado)")

# Experiencia laboral
st.header("💼 Experiencia Laboral")
st.write("**Apoyo administrativo / Guía PUCP - Oficina de Admisión**")
st.write("📅 Marzo 2024 - Marzo 2025")
st.write("- Representar a la PUCP en diferentes instituciones educativas de nivel básico")

# Voluntariado
st.header("🤝 Voluntariado")
st.write("**Community Manager en Idiomas Sin Fronteras**")
st.write("📅 Noviembre 2024 - Actualidad")
st.write("- Planificación de contenidos")
st.write("- Análisis de estadísticas")
st.write("- Diseño de posts para redes sociales")

# Intereses
st.header("✨ Intereses")
st.write("- Escritura")
st.write("- Fotografía")
st.write("- Arte")

# Pie de página
st.markdown("---")
st.caption("Aplicación creada con ❤️ por María Fe usando Streamlit")